services:
  mongodb:
    image: mongo:latest
    container_name: pjc-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-CHANGEME_UNSAFE_DEFAULT}
    networks:
      - pjc-network
      
  backend:
    build: ./backend
    container_name: pjc-backend
    restart: always
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:CHANGEME_UNSAFE_DEFAULT@mongodb:27017/protection-juridique?authSource=admin}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-5002}
      - SKIP_DATA_INIT=${SKIP_DATA_INIT:-false}
    depends_on:
      - mongodb
    volumes:
      - ./backend/templates:/app/templates
      - ./backend/temp:/app/temp
    networks:
      - pjc-network
      
  frontend:
    build: ./client
    container_name: pjc-frontend
    restart: always
    ports:
      - "80:80"  # Écoute sur port 80
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-/api}  # Utilise le proxy
    networks:
      - pjc-network
      
networks:
  pjc-network:
    driver: bridge
volumes:
  mongodb_data: